import { createFileRoute } from "@tanstack/react-router";
import { Link } from "@tanstack/react-router";
import { Mail, FileText, ListChecks, Search, MessageSquare, Sparkles } from "lucide-react";
import { PageShell } from "@/components/page-shell";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "Dashboard — Aria" },
      { name: "description", content: "Your AI workplace productivity dashboard." },
    ],
  }),
  component: Index,
});

const tools = [
  { to: "/email", icon: Mail, title: "Smart Email Generator", desc: "Draft polished emails from a short brief." },
  { to: "/meetings", icon: FileText, title: "Meeting Notes Summarizer", desc: "Turn raw notes into decisions and action items." },
  { to: "/tasks", icon: ListChecks, title: "AI Task Planner", desc: "Break goals into prioritized, scheduled tasks." },
  { to: "/research", icon: Search, title: "AI Research Assistant", desc: "Get structured briefings on any topic." },
  { to: "/chat", icon: MessageSquare, title: "AI Chatbot", desc: "Conversational copilot for ad-hoc work." },
] as const;

function Index() {
  return (
    <PageShell
      title="Welcome back"
      description="Pick a tool to automate your next workplace task."
    >
      <div
        className="mb-8 overflow-hidden rounded-xl border p-6 text-primary-foreground shadow-[var(--shadow-elegant)]"
        style={{ backgroundImage: "var(--gradient-primary)" }}
      >
        <div className="flex items-center gap-2 text-xs font-medium uppercase tracking-wider opacity-90">
          <Sparkles className="h-4 w-4" /> Powered by Aria AI
        </div>
        <h2 className="mt-2 max-w-2xl text-2xl font-semibold sm:text-3xl">
          Get hours back every week.
        </h2>
        <p className="mt-1 max-w-2xl text-sm opacity-90">
          Generate, summarize, plan, and research — all in one workspace.
        </p>
      </div>

      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        {tools.map((t) => (
          <Link
            key={t.to}
            to={t.to}
            className="group rounded-xl border bg-card p-5 shadow-[var(--shadow-soft)] transition hover:-translate-y-0.5 hover:border-primary/40 hover:shadow-[var(--shadow-elegant)]"
          >
            <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-accent text-accent-foreground transition group-hover:bg-primary group-hover:text-primary-foreground">
              <t.icon className="h-5 w-5" />
            </div>
            <h3 className="mt-4 text-base font-semibold text-foreground">{t.title}</h3>
            <p className="mt-1 text-sm text-muted-foreground">{t.desc}</p>
          </Link>
        ))}
      </div>

      <p className="mt-8 text-xs text-muted-foreground">
        Responsible AI: outputs are generated by an AI model and may be inaccurate. Review before
        sharing externally.
      </p>
    </PageShell>
  );
}
