import type { ReactNode } from "react";

export function PageShell({
  title,
  description,
  children,
  actions,
}: {
  title: string;
  description?: string;
  children: ReactNode;
  actions?: ReactNode;
}) {
  return (
    <div className="mx-auto w-full max-w-6xl px-4 py-6 sm:px-6 lg:px-8">
      <header className="mb-6 grid grid-cols-[minmax(0,1fr)_auto] items-start gap-4">
        <div className="min-w-0">
          <h1 className="truncate text-2xl font-semibold tracking-tight text-foreground sm:text-3xl">
            {title}
          </h1>
          {description && (
            <p className="mt-1 text-sm text-muted-foreground">{description}</p>
          )}
        </div>
        {actions && <div className="shrink-0">{actions}</div>}
      </header>
      {children}
    </div>
  );
}

export function ResultCard({
  value,
  onChange,
  placeholder = "AI output will appear here. Edit freely before using it.",
}: {
  value: string;
  onChange: (v: string) => void;
  placeholder?: string;
}) {
  return (
    <div className="rounded-lg border bg-card shadow-[var(--shadow-soft)]">
      <div className="flex items-center justify-between border-b px-4 py-2">
        <span className="text-xs font-medium uppercase tracking-wider text-muted-foreground">
          Editable output
        </span>
        <div className="flex gap-2">
          <button
            type="button"
            onClick={() => navigator.clipboard.writeText(value)}
            disabled={!value}
            className="rounded-md border px-2 py-1 text-xs hover:bg-accent disabled:opacity-40"
          >
            Copy
          </button>
          <button
            type="button"
            onClick={() => onChange("")}
            disabled={!value}
            className="rounded-md border px-2 py-1 text-xs hover:bg-accent disabled:opacity-40"
          >
            Clear
          </button>
        </div>
      </div>
      <textarea
        value={value}
        onChange={(e) => onChange(e.target.value)}
        placeholder={placeholder}
        className="min-h-[320px] w-full resize-y bg-transparent p-4 font-mono text-sm leading-relaxed text-foreground outline-none"
      />
    </div>
  );
}

export function AiDisclaimer() {
  return (
    <p className="mt-4 text-xs text-muted-foreground">
      Responsible AI: outputs are generated by an AI model and may contain inaccuracies or biases.
      Always review, verify facts, and remove confidential information before sharing.
    </p>
  );
}